version: '3.8'
services:
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - .env.local
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - .env.local
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
